#!/bin/bash
# Check if started as root
if [ "$EUID" -ne 0 ]
then echo "ERROR: This script must be run with root privileges"
    exit
fi
(
    if ! umount /dev/mapper/luks
    then
        exit
    fi
)
(
    if ! cryptsetup luksClose luks
    then
        exit
    fi
)
echo "Encrypted usb-stick is no longer mounted"