#!/bin/bash
# Check if started as root
if [ "$EUID" -ne 0 ]
then echo "ERROR: This script must be run with root privileges"
    exit
fi
# Check if /mnt is empty
if ! [ -z "$(ls -A /mnt)" ]
then
    if ! [[ -d "/mnt/encrypted" ]]
    then
        echo "Error: Unable to mount, /mnt is not empty"
        exit
    fi
fi
# Check if /mnt/enrypted exists
if ! [[ -d "/mnt/encrypted" ]]
then 
    mkdir /mnt/encrypted
    echo "Created directory /mnt/encrypted"
fi
# Check if /mnt/encrypted is empty
if ! [ -z "$(ls -A /mnt/encrypted)" ]
then
    echo "Error: Unable to mount, /mnt/encrypted is not empty"
    exit 
fi
(
    cryptsetup luksOpen /dev/sda luks
)
(
    mount /dev/mapper/luks /mnt/encrypted
)
echo "Encrypted usb-stick is now mounted on /mnt/encrypted"